### PR TITLE
Fix UI output

### LINKED ISSUE #57: For "Withdraw unbonded" tx, display the "Num slashing span" screen in expert mode only
It's all in the title.

As this parameter is very technical it will confuse most users so we should keep it in expert mode.

### PR DESCRIPTION
**Pull request by raynaudoe**
- Fix balance output
- Update Zemu tests
- Add support for expert field values on methods. Closes #57

### CODE REVIEW

File: app/src/parser_impl.c [hunk 1]
```diff
@@ -316,8 +317,9 @@ parser_error_t  _appendCoinSymbol(char *value) {
     MEMZERO(buffer, sizeof(buffer));
     strcat(buffer, COIN_TICKER);
     strcat(buffer, " ");
-    strcat(buffer,value);
-    strcpy(value, buffer);
+    strcat(buffer, value);
+    // print length: strlen(value) + strlen(COIN_TICKER) + strlen(" ") + strlen("\0")
+    snprintf(value, strlen(value) + strlen(COIN_TICKER) + 2, "%s", buffer);
```
Comment (jleni) [inline app/src/parser_impl.c:322]: Here we should know the maximum size for value and limit snprintf with that limit
maybe adding something like 
```
if (strlen(buffer) + 2 + strlen(COIN_TICKER) > outValLen-1) return error
```

**Review by jleni — CHANGES_REQUESTED** [review]

File: app/src/parser_impl.c (hunk 1 above)
Comment (raynaudoe) [reply app/src/parser_impl.c]: Ok, I did a refactor of this part. 
`_toStringCompactInt` now accepts a prefix value which for balances types will be `COIN_TICKER`.
